name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.*'
        host: 'linux'
        target: 'desktop'
        modules: 'qtcore qtwidgets'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MyCppPlanner
        path: ${{github.workspace}}/build/MyCppPlanner
